### ISSUE TITLE
fyi

### ISSUE THREAD

**Issue by johndpope** [demmys/playlist#1]
PlaylistManagerModel
![screen shot 2016-11-29 at 23 18 32](https://cloud.githubusercontent.com/assets/289994/20739593/09e1db38-b68a-11e6-9ee1-2eb0ffc93a72.png)

this tripped up when I selected a song / then it said 'select song to add'
![screen shot 2016-11-29 at 23 20 52](https://cloud.githubusercontent.com/assets/289994/20739614/5145fe0a-b68a-11e6-97d6-d680f7e9dcba.png)

probably no need for weak reference.
 private var _delegate: PlaylistManagerModelDelegate!

I recommend you do some code review on this
https://github.com/johndpope/AudioPlayerManager
something is wrong with design on playlist object. 

in the songTableViewController
rather than using seque - just use this method

 override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: "NowPlaying") as? PlayerViewController

        let info = _audioInfoList.get(inSection: indexPath.section, index: indexPath.row)
        vc.mediaItem = info 
        self.navigationController?.pushViewController(vc, animated: true)

        
    }
    
then cut the segue. I never use them.
<img width="443" alt="screen shot 2016-11-29 at 23 48 05" src="https://cloud.githubusercontent.com/assets/289994/20740058/215d67e2-b68e-11e6-9cd9-3fc8aa9903a0.png">

**Comment by akkyie** [comment]
The weak reference is not the actual reason of the crash. This happens because returning `nil` in a failable initializer always invokes `deinit`. You can confirm this behavior with a few lines of code:
```swift
class Test {
	init?(fail: Bool) {
		if fail { return nil }
	}
	deinit {
		print("deinit")
	}
}

let test = Test(fail: true)
// prints "deinit"
```

Therefore, you SHOULD NOT use IUO types for class properties even if they always be replaced by real values in the initializer, especially when you make it failable.

**Comment by johndpope** [comment]
thanks @Akkyie
